### ISSUE TITLE
Support footnotes

### ISSUE THREAD

**Issue by KusakabeShi** [jrnewton/github-readme-to-html#3]
In this readme.md https://github.com/KSKBpage/dn42page/blob/main/README.md

What I get: 
![image](https://user-images.githubusercontent.com/73118488/147860414-089646ce-4d1f-4511-bd8d-e6dee939432f.png)
![image](https://user-images.githubusercontent.com/73118488/147860416-c338b399-b30c-4098-8601-17e589a31e1a.png)

What I expected:
![image](https://user-images.githubusercontent.com/73118488/147860424-cead6b1d-e2f9-49f3-9ad2-dc64db927fc4.png)
![image](https://user-images.githubusercontent.com/73118488/147860425-be97ec83-e430-4c7a-b85d-6e1987e467d6.png)

**Comment by jrnewton** [comment]
Hi @KusakabeSi  - 

I've committed VERY basic footnote support.  It does not support auto-number or backlinks as shown in your example though. 

If you need more advanced formatting I will suggest you look at https://github.com/phseiff/github-flavored-markdown-to-html which has full support of GH markdown.

**Comment by jrnewton** [comment]
Released in v1.0.6
