### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by taoliujun** [jrnewton/github-readme-to-html#5]
There is a bug show `env: node\r: No such file or directory` when i used below.

`
yarn add -D github-readme-to-html

yarn github-readme-to-html
`

 Because the file `./node_modules/github-readme-to-html/index.js`  with DOS-style newlines. fix it below.

`
vim index.js

:se ff=unix
:wq
`

**Comment by jrnewton** [comment]
Hi @taoliujun - 

What OS are you using and what version of yarn?  I'd like to reproduce it first before I convert the file line endings.

**Comment by taoliujun** [comment]
> Hi @taoliujun -
> 
> What OS are you using and what version of yarn? I'd like to reproduce it first before I convert the file line endings.

mac osx 11.5 (20G71)

yarn 1.22.17

**Comment by jrnewton** [comment]
Hey @taoliujun - 

Please install 1.0.7 beta and verify that it works for you.

`yarn add -D github-readme-to-html@beta `

**Comment by jrnewton** [comment]
I found an iMac to test on.  Fix released in 1.0.7.
