### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by geelen** [jrnewton/github-readme-to-html#9]
I saw https://github.com/KrauseFx/markdown-to-html-github-style/issues/1 and https://github.com/KrauseFx/markdown-to-html-github-style/pull/8 but no updates in a couple of years.

Do you think it's worth trying to get that shipped in that repo or would it make more sense in this one?

**Comment by jrnewton** [comment]
@geelen - pretty sure I've got it ready.  You can test via the 9-syntax-highlighting branch.  

See https://github.com/jrnewton/github-readme-to-html/tree/9-syntax-highlighting#testing for instructions on testing a local NPM module (if you've never done it before) :)

**Comment by geelen** [comment]
It's getting close! Had a bit of trouble following the instructions, it was a lot easier to just checkout that branch, then do:

```
npm i
./index.js -i ../../npx-import/README.md
```

Result isn't quite right though, font for typescript is off

<img width="415" alt="image" src="https://user-images.githubusercontent.com/23264/183906075-cd534ba6-88fe-4b87-b08a-1be90e2f2f81.png">

And code blocks without a language still get some words highlighted:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/23264/183906215-82d8b771-9157-4bc7-92b6-f87ab07689b0.png">

Also there's a weird `hljs` being injected on all of those ones, weird!

I also got a couple of little warnings when running it:

```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

**Comment by jrnewton** [comment]
Okay - let me look into the "hljs" bits being injects, and updating hljs usage to remove the warnings.  

What font did you expect for ts?

**Comment by geelen** [comment]
Anything monospaced is fine.

Also, I forgot to link the live version: https://d4b99584.npx-import.pages.dev/

If you inspect the element, you can see the `code` element has: font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, Courier, monospace;

but then there's some `*` css rule that's overriding it for everything inside: 
![image](https://user-images.githubusercontent.com/23264/184121492-6eab62db-089e-45af-8692-b8562b252879.png)

I think you want this to be `body`, not `*`: https://github.com/jrnewton/github-readme-to-html/blob/main/index.html#L309-L311

**Comment by jrnewton** [comment]
@geelen - I think I've fixed everything.  Give it a shot please :)

**Comment by geelen** [comment]
Looks great! https://readme-syntax-highlighting.npx-import.pages.dev/

Let me know when you've released it, I'll merge this branch. Thanks!

**Comment by jrnewton** [comment]
My pull request had a code scan alert, and while researching the proper fix I discovered this: https://github.com/Bloggify/showdown-highlight

Test output looks good to me and it will be less code to maintain.  

Give it a run from https://github.com/jrnewton/github-readme-to-html/tree/9-syntax-highlighting-take2

**Comment by geelen** [comment]
Ah, one small thing. It looks like there's a default language in place? I'm seeing highlights in sections like this:

![image](https://user-images.githubusercontent.com/23264/186183159-dfd82708-60f0-4bec-b007-a570206c33ff.png)

For this input:

![image](https://user-images.githubusercontent.com/23264/186183215-7d708e44-3535-4d54-8836-425cd8239fa5.png)

Ideally, unless a language is specified, words like `is`, `not`, `into`, `skep` shouldn't be highlighted at all. Github does the right thing:

![image](https://user-images.githubusercontent.com/23264/186183598-ab3f5792-cac7-4480-825d-30fe54cc80c3.png)

**Comment by jrnewton** [comment]
I just tested with both branches, and the behavior seems to be the same, so seems to be behavior in hljs.  The lib supports lang "nohighlight" but that didn't work.  Lang "text" might work for you though.  Can you give it try please?

**Comment by geelen** [comment]
Yup, `text` looks good: 

![image](https://user-images.githubusercontent.com/23264/186233011-c1f82fba-83ac-46f2-a6a9-992d23f65c6c.png)

Weird that it's getting a default, though. The words I can see highlighted in the old version (https://54873ca5.npx-import.pages.dev/) and their classes are:

```
is — hljs-built_in
'll have to compile imagemagick! — hljs-comment
not — hljs-built_in
to — hljs-keyword
into — hljs-keyword
skip — hljs-keyword
step — hljs-keyword
in — hljs-keyword
save — hljs-built_in
import — hljs-keyword
add — hljs-built_in
@latest — hljs-symbol
@6 — hljs-symbol
odd — hljs-built_in
log — hljs-built_in
split — hljs-built_in
package — hljs-keyword
p — hljs-selector-tag
$LOG_NPX_DIR — hljs-variable
```

That's... super weird. Single quote comments? Detecting `p` as `hljs-selector-tag`? It's like it's just trying to find _something_ to style things with...

Can you set the default to `text` somehow when you invoke `hljs`, if it's not otherwise specified?

**Comment by geelen** [comment]
> It's like it's just trying to find something to style things with...

Ha! The first one looks like it thought I was writing `vbscript`, for some reason:

```vbscript
❯ node ./index.js --filename=image.png

This is a PNG! We'll have to compile imagemagick!
[NPXI] imagemagick-utils not available locally. Attempting to use npx to install temporarily.
[NPXI] Installing... (npx -y -p imagemagick-utils@^1.1.0)
[NPXI] Installed into /Users/glen/.npm/_npx/8cac855b1579fd07/node_modules.
[NPXI] To skip this step in future, run: pnpm add -D imagemagick-utils@^1.1.0
Done!
```

But the others are all different. So weird!

**Comment by jrnewton** [comment]
My preference would be to use the showdown highlight extension, which does not support a default lang, but let me see if anyone has raised the issue in that project, and either way maybe I can contribute the enhancement there.  It's pretty straightforward code-wise.

**Comment by jrnewton** [comment]
I'm going to merge the showdown hljs extension code and then open a PR with them to try for the default lang... even without that, I like the support the hljs extension provides.

**Comment by jrnewton** [comment]
Closing this issue and will open a new issue for the specific default lang requirement.
